### ISSUE TITLE
Milestone 1 tasks

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-py#5]
In this milestone, we focus on setting up *main* branch that can work with existing 7.10.2 version of ODFE
- [x] Delete all older branches  < 7.10 
- [x] Delete all released tags
- [x] Delete *main* branch(this branch potentially tracks of all 8.x features as well)
- [x] create *main* branch from 7.x branch
- [x] Remove product checker commit if present (this is required to make clients work with oss cluster)
- [x] Copy template files related to OpenSearch guidelines.
- [x] set up CI and ensure tests pass for Elasticsearch OSS Docker image. This means all the test cases related to oss features from 7.10.2 executes successfully.
