### ISSUE TITLE
Milestone 3 tasks

### ISSUE THREAD

**Issue by rushiagr** [opensearch-project/opensearch-py#8]
In this milestone, we focus on refactoring changes and make it work with OpenSearch 1.0.0 clusters

- [ ] Namespace changes and other refactoring on *main* branch to support OpenSearch
- [ ] CI is expected to pass for OpenSearch and OpenDistro with and with out security
- [ ] Repo should be made public
